# Generated by Django 3.2.5 on 2022-02-09 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_threadmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='receiver_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.user'),
        ),
    ]
